// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxAw-f-vK9jb1lNGVCBYc5thkqThyvQdc',
    appId: '1:94384910416:web:d8fa9c050377dd85306155',
    messagingSenderId: '94384910416',
    projectId: 'xinzzui-x',
    authDomain: 'xinzzui-x.firebaseapp.com',
    storageBucket: 'xinzzui-x.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOmmceasPBAeA-A1Rl83Rt8WChH-2L7zY',
    appId: '1:94384910416:android:25f21213a244eb2f306155',
    messagingSenderId: '94384910416',
    projectId: 'xinzzui-x',
    storageBucket: 'xinzzui-x.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxAw-f-vK9jb1lNGVCBYc5thkqThyvQdc',
    appId: '1:94384910416:web:42798ed48163785c306155',
    messagingSenderId: '94384910416',
    projectId: 'xinzzui-x',
    authDomain: 'xinzzui-x.firebaseapp.com',
    storageBucket: 'xinzzui-x.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6R7ddwtY-dpdbw62g_CDxsb2xd-PDEiM',
    appId: '1:94384910416:ios:912206a11376c8d9306155',
    messagingSenderId: '94384910416',
    projectId: 'xinzzui-x',
    storageBucket: 'xinzzui-x.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6R7ddwtY-dpdbw62g_CDxsb2xd-PDEiM',
    appId: '1:94384910416:ios:912206a11376c8d9306155',
    messagingSenderId: '94384910416',
    projectId: 'xinzzui-x',
    storageBucket: 'xinzzui-x.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

}